//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Save_Editor.Resources.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] avatars {
            get {
                object obj = ResourceManager.GetObject("avatars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] checkpoints {
            get {
                object obj = ResourceManager.GetObject("checkpoints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] crafters {
            get {
                object obj = ResourceManager.GetObject("crafters", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] difficulty {
            get {
                object obj = ResourceManager.GetObject("difficulty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] distribution {
            get {
                object obj = ResourceManager.GetObject("distribution", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] effects {
            get {
                object obj = ResourceManager.GetObject("effects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] elements {
            get {
                object obj = ResourceManager.GetObject("elements", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] items {
            get {
                object obj = ResourceManager.GetObject("items", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] journal {
            get {
                object obj = ResourceManager.GetObject("journal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] maps {
            get {
                object obj = ResourceManager.GetObject("maps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small cuddly Nexomon enveloped in fluffy fur that helps it keep balanced on its tiny legs.
        ///This Nexomon is usually very distracted making soft noises and mumbling while absorbed in its thoughts. However, it is among the most intelligent of Nexomon.
        ///When a Cubdy evolves into Lukuma it becomes very grumpy and aggressive, as well as territorial. Yet, it tends to space out from time to time.
        ///A scorching pebble with a magma core which also forms its one eye. When chasing it, be careful not to trip on its tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monster_descriptions {
            get {
                return ResourceManager.GetString("monster_descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloddy
        ///cubdy
        ///lukuma
        ///kolphur
        ///sulphlo
        ///moltano
        ///bloopish
        ///glimoory
        ///glamoory
        ///spikus
        ///spikarm
        ///thornox
        ///pebglem
        ///gemock
        ///gemaxar
        ///heliwurm
        ///helipa
        ///heliventus
        ///zumble
        ///zasp
        ///zappnic
        ///branipus
        ///cerebrius
        ///octollect
        ///skerdi
        ///aferaid
        ///dreddiful
        ///griff
        ///griffgar
        ///lioness
        ///flizard
        ///stinger
        ///moonsting
        ///sunknight
        ///faucefant
        ///draniphant
        ///tuskant
        ///shromporo
        ///shrombrela
        ///shromboff
        ///fortle
        ///fortoise
        ///fortank
        ///larkito
        ///moska
        ///sakka
        ///chibbit
        ///xotor
        ///odiborg
        ///dreaver
        ///dredmore
        ///dredrone
        ///ghouze
        ///mazecter
        ///taipluff
        ///fis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monster_names {
            get {
                return ResourceManager.GetString("monster_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monsters {
            get {
                object obj = ResourceManager.GetObject("monsters", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pets {
            get {
                object obj = ResourceManager.GetObject("pets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] quests {
            get {
                object obj = ResourceManager.GetObject("quests", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rarity {
            get {
                object obj = ResourceManager.GetObject("rarity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shops {
            get {
                object obj = ResourceManager.GetObject("shops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals high Fire-type damage with great accuracy.
        ///Deals Ghost-type damage with a 40% chance to inflict leech.
        ///Deals Psychic-type damage with a 25% critical hit rate.
        ///Increases DEF by 25%.
        ///Creates a fire barrier for 3 turns, reducing Fire-type damage received by 50%.
        ///Creates a wind barrier for 3 turns, reducing Wind-type damage received by 50%.
        ///Has a 35% chance to inflict bind. Does not require much stamina.
        ///Has a 35% chance to inflict paralyze.
        ///Deals high Plant-type damage with a 10% chance to inflic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skill_descriptions {
            get {
                return ResourceManager.GetString("skill_descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion
        ///Soul Feeder
        ///Psychic Blast
        ///Barrier
        ///Fire Barrier
        ///Wind Barrier
        ///Fire Cage
        ///Creep
        ///Blooming Spores
        ///Power Up
        ///Quick Feet
        ///Elemental Up
        ///Resistance
        ///Raging Focus
        ///Sky Blessing
        ///Burn
        ///Incinerate
        ///Disruption Ray
        ///Mud Attack
        ///Drill
        ///EMP
        ///Darkness
        ///Electric Bomb
        ///Fire Claw
        ///Flame
        ///Flame Breath
        ///Flame Column
        ///Freeze
        ///Grasping Root
        ///Piercing Root
        ///Heal
        ///Stamina Surge
        ///Spiritual Boost
        ///Healing Water
        ///Tropical Rain
        ///Howling Winds
        ///Hydro Sphere
        ///Water Blast
        ///Leaf Dance
        ///Mystic Aroma
        ///Pulse Storm
        ///Electric  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skill_names {
            get {
                return ResourceManager.GetString("skill_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] skills {
            get {
                object obj = ResourceManager.GetObject("skills", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tamers {
            get {
                object obj = ResourceManager.GetObject("tamers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] trades {
            get {
                object obj = ResourceManager.GetObject("trades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] warpstones {
            get {
                object obj = ResourceManager.GetObject("warpstones", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
